### ISSUE TITLE
Exception in Guzzle

### ISSUE THREAD

**Issue by diamo1213** [thephpleague/omnipay#369]
Hi guys,
could you give me hand?

I get an exception using Pin:

Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35: Unknown SSL protocol error in connection to test-api.pin.net.au:443 [url] https://test-api.pin.net.au/1/charges' in /home/e-gove/public_html/b2b/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359 Stack trace: #0 /home/e-gove/public_html/b2b/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array) #1 /home/e-gove/public_html/b2b/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array) #2 /home/e-gove/public_html/b2b/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages() #3 /home/e-gove/public_html/b2b/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): G/home/e-gove/public_html/b2b/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php359

**Comment by delatbabel** [comment]
PIN have recently changed their API to require TLS 1.2 for test, and will require TLS 1.2 for production as of the end of this month.  You will need to update your OpenSSL/libcurl libraries to support TLS 1.2.
