### ISSUE TITLE
Webhooks Testing Gives Errors

### ISSUE THREAD

**Issue by ParadiseStudios** [thephpleague/omnipay#484]
Assumes:
Omnipay is setup correctly.
Omnipay makes a successful transaction to Braintree.
MerchantID, PublicKey & PrivateKey are set correctly.

```
$sampleNotificationSignature = 'WITHHELD';
$sampleNotificationPayload = 'WITHHELD';
use Omnipay\Omnipay;
$gateway = Omnipay::create('Braintree');
$gateway->setPrivateKey('WITHHELD');
$gateway->setPublicKey('WITHHELD');
$gateway->setMerchantId('WITHHELD');
$gateway->setTestMode(TRUE);
$notification = $gateway->parseNotification([
    'bt_signature'  => $sampleNotificationSignature,
    'bt_payload'    => $sampleNotificationPayload
])->send();
```

When trying to test WebHooks from Braintree, POST from the test url results in the following errors...

```
Fatal error: Uncaught Braintree\Exception\Configuration: Braintree\Configuration::merchantId needs to be set (or accessToken needs to be passed to Braintree\Gateway). in /vendor/braintree/braintree_php/lib/Braintree/Configuration.php:254

Stack trace:
#0 /vendor/braintree/braintree_php/lib/Braintree/WebhookNotificationGateway.php(10): Braintree\Configuration->assertHasAccessTokenOrKeys()
#1 /vendor/braintree/braintree_php/lib/Braintree/Gateway.php(257): Braintree\WebhookNotificationGateway->__construct(Object(Braintree\Gateway))
#2 /vendor/braintree/braintree_php/lib/Braintree/WebhookNotification.php(35): Braintree\Gateway->webhookNotification()
#3 /vendor/omnipay/braintree/src/Gateway.php(281): Braintree\WebhookNotification::parse('DETAILS HIDDEN')
#4 braintree.php(27 in /vendor/braintree/braintree_php/lib/Braintree/Configuration.php on line 254
```

https://stackoverflow.com/questions/48843652/omnipay-braintree-webhooks-testing-gives-errors

**Comment by delatbabel** [comment]
This issue looks like it's specific to the braintree gateway so should be raised in that gateway's repository.  It doesn't look like a generic Omnipay error.

**Comment by ParadiseStudios** [comment]
https://github.com/thephpleague/omnipay-braintree/issues/37
